---
title: "K_means"
output: html_document
date: "2022-08-17"
---

## Install Packages

```{r setup, include=FALSE}

#install.packages("factoextra")
#install.packages("stats")
#install.packages("janitor")
#install.packages("ClusterR")
#install.packages("cluster")
  
# Loading package
library(ClusterR)
library(cluster)
library(factoextra)
library(stats)
library(janitor)
library(dplyr)
library(tidyverse)  
library(cluster)

```


## USA Arrests DataSet (R DataSet)

```{r}
#read in data 
df <- USArrests %>% na.omit(df)

## Scaling and standardising 
df <- scale(df)
head(df)

#compute distance matrix
distance <- get_dist(df)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))


## K-Means clustering 

k2 <- kmeans(df, centers = 2, nstart = 25)
str(k2)
k2

#If there are more than two dimensions (variables) fviz_cluster will perform principal component analysis (PCA) and plot the data points according to the first two principal components that explain the majority of the variance.

#visualise 
fviz_cluster(k2, data = df)


#Or you could use standard pairwise scatter plots 
df %>%
  as_tibble() %>%
  mutate(cluster = k2$cluster,
         state = row.names(USArrests)) %>%
  ggplot(aes(UrbanPop, Murder, color = factor(cluster), label = state)) +
  geom_text()
```



## Customer Data 

The data set refers to clients of a wholesale distributor. It includes the annual spending in monetary units (m.u.) on diverse product categories

```{r}
#read in data
customer <- read.csv("Wholesale customers data.csv") %>% clean_names()

# Fitting k-means clustering model
set.seed(240) # Setting seed
kmeans.re <- kmeans(customer, centers = 3, nstart = 20)
kmeans.re

#cluster identification?
kmeans.re$cluster
  
# Confusion Matrix
cm <- table(customer$region, kmeans.re$cluster)
cm
  
# Model Evaluation and visualization
plot(customer[c("grocery", "frozen")])
plot(customer[c("grocery", "frozen")], 
     col = kmeans.re$cluster)
plot(customer[c("grocery", "frozen")], 
     col = kmeans.re$cluster, 
     main = "K-means with 3 clusters")
  
## Plotiing cluster centers
kmeans.re$centers
kmeans.re$centers[, c("grocery", "frozen")]
  
# cex is font size, pch is symbol
points(kmeans.re$centers[, c("grocery", "frozen")], 
       col = 1:3, pch = 8, cex = 3) 
  
## Visualizing clusters
y_kmeans <- kmeans.re$cluster
clusplot(customer[, c("grocery", "frozen")],
         y_kmeans,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Cluster iris"),
         xlab = 'grocery',
         ylab = 'frozen')

```













